name: Build Kivy APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y zip unzip openjdk-17-jdk
          pip install --upgrade pip
          pip install buildozer cython
          pip install kivy==2.3.0 kivymd

      - name: Initialize Buildozer
        run: buildozer init

      - name: Overwrite buildozer.spec
        run: |
          cat > buildozer.spec <<EOF
[app]
title = Khan Optical
package.name = khanoptical
package.domain = org.khan.optical
source.dir = .
source.include_exts = py,png,jpg,kv,atlas
version = 1.0
requirements = python3,kivy==2.3.0,kivymd
orientation = portrait
fullscreen = 0
android.permissions = INTERNET
android.api = 33
android.minapi = 21
android.ndk = 25b
android.archs = arm64-v8a,armeabi-v7a
android.build_tools_version = 34.0.0
android.gradle_dependencies = com.google.android.material:material:1.2.1
EOF

      - name: Build APK
        run: buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: khan-optical-apk
          path: bin/*.apk
